### ISSUE TITLE
app.npm undefined

### ISSUE THREAD

**Issue by onokumus** [node-base/base-npm#1]
``` js
var npm = require('base-npm');
var Base = require('base');

var app = new Base();

app.use(npm());

console.log(app.npm); // undefined
```

But;

``` js
var bower = require('base-bower');
var Base = require('base');

var app = new Base();

app.use(bower());

console.log(app.bower);
```

konsole output;

``` sh
{ [Function: bower]
  install: [Function: install],
  latest: [Function],
  save: [Function],
  saveDev: [Function] }

```

what's wrong?

**Comment by doowb** [comment]
Take a look at the [usage on base-npm-prompt](https://github.com/node-base/base-npm-prompt#usage). I'll update the examples in the readme here and add that same message.

Basically, this plugin will only be registered on "applications". You can specify that `app` is an application by creating `app` like this:

``` js
var app = new Base({isApp: true});
```

**Comment by onokumus** [comment]
@doowb 

it's ok. thanks

**Comment by jonschlinkert** [comment]
To add to what @doowb said, plugins can (optionally) automatically propagate down child instances. The pattern of using `isApp` is a pattern that we use on some plugins to allow them to be "smart" about what instances they are registered on.
