### ISSUE TITLE
Use `app.cwd`

### ISSUE THREAD

**Issue by doowb** [node-base/base-npm#2]
When spawning the `npm` command, we should use `app.cwd || process.cwd()` since a user may have changed the `cwd` with their options. See https://github.com/generate/generate-install/issues/1#issuecomment-244407949 for more details.

I'll try to get a fix in soon.

**Comment by tunnckoCore** [comment]
It seems it uses it in [index.js#L226-L236](https://github.com/node-base/base-npm/blob/master/index.js#L226-L236) - the `pkg`, `pkgPath` and `pkgData` functions.

Any process on this? I can PR, but not sure what.

> When spawning the npm command

You mean, before the spawning, with `.chdir`?

**Comment by jonschlinkert** [comment]
@doowb is this resolved by that pr? Looks great!

**Comment by doowb** [comment]
Yeah, [this commit](https://github.com/node-base/base-npm/commit/42b8131996d6a2e5c1e0ec330e7efdfce708515f) closes this issue.

> You mean, before the spawning, with .chdir?

@tunnckoCore that's what I was thinking at first, but [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) has a `cwd` option that can be used. I had updated this locally and forgot to push up the changes.
